version: '3.8'

services:
  ai-agents:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "8888:8888"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/src/__pycache__
    depends_on:
      - redis
    restart: unless-stopped
    stdin_open: true
    tty: true

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: Database for persistence
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ai_agents
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: 